### ISSUE TITLE
Issue with connection being rejected when trying to connect via steam

### ISSUE THREAD

**Issue by termi17385** [tom-weiland/RiptideSteamTransport#1]
After creating a lobby client attempts to start riptide and join the server through steam, joins successfully but then gets rejected with unknown reason logged to console.

Unknown reason = already connected.

![image](https://user-images.githubusercontent.com/66066987/208613565-b447ed70-c779-419c-9ef8-50bed2c29f3e.png)

**Comment by tom-weiland** [comment]
Notes for myself so I don't forget:
- The reject reason being logged as "unknown" is due to RiptideNetworking/Riptide#84.
- [Explanation of probable](https://discord.com/channels/409147571928563712/1052099979491147776/1054664540018724926) cause in Discord forum post.
